### ISSUE TITLE
SPLoaderError.loadComponentError

### ISSUE THREAD

**Issue by huynp** [sebastienlevert/spfx-ng-webparts#4]
I try build and run hello-world example and get this error.
`***Failed to load component "ee022f6c-5868-409e-918d-aa684ef065c7" (HelloWorldWebPart).
Original error: ***Failed to load entry point from component "ee022f6c-5868-409e-918d-aa684ef065c7" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/ee022f6c-5868-409e-918d-aa684ef065c7_0.0.1
	Object(...) is not a function

***INNERERROR:
***Failed to load entry point from component "ee022f6c-5868-409e-918d-aa684ef065c7" (HelloWorldWebPart).
Original error: Error loading https://component-id.invalid/ee022f6c-5868-409e-918d-aa684ef065c7_0.0.1
	Object(...) is not a function
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:24)
    at new SPLoaderError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:28)
    at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:21)
    at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3743:21)
    at https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:38`

Look like there some update on SharePoint Framework that broke the code. I try other the example get the same error.

**Comment by sebastienlevert** [comment]
You just git clone this repo, npm install and you get this result using the Local Workbench?
